/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/card/update': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['updateCard']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/verify-user': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['verifyUser']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/reset-password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['resetPassword']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/manager/verify-user/{authUserId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['verifyUserByManager']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/manager/unlock-user': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['unlockUserByManager']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/manager/block-user': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['blockUserByManager']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/change-password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['changePassword']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/admin/change-auth-user-role': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['changeAuthUserRole']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/account/unfreeze/{accountId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['unfreezeAccount']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/account/manager/unfreeze/{accountId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['unfreezeAccountByManager']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/account/manager/freeze/{accountId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['freezeAccountByManager']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/account/freeze/{accountId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['freezeAccount']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/user/recipient-info': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['getRecipientInfo']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/user/manager/user-info': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['getUserInfoByManager']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/transaction/creat-transaction': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['createTransaction']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/card/create': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['createCard']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/signup': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['signup']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/refresh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['refresh']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/forget-password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['forgetPassword']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/account/withdraw': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['withdrawAccount']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/account/topUp': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['topUpAccount']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/account/create': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['createAccount']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/notification/notifications/mark-as-readed': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch: operations['markAsReaded']
    trace?: never
  }
  '/user/user-info': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getUserInfo']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/user/manager/all-user-info': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getAllUserInfo']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/user/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getUserHealth']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/transaction/user/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getTransactionsByMe']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/transaction/manager/user/{userId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getTransactionsByUserIdByManager']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/transaction/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getTransactionHealth']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/notification/notifications': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getNotifications']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/notification/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getNotificationHealth']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/card/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getCardHealth']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/oauth/google': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['googleLogin']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getAuthHealth']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/asyncapi.yaml': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['asyncApiYaml']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/account/manager/all-accounts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getAllAccountsWithCards']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/account/manager/accounts/{ownerUserId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getAccountsWithCardsByOwnerIdByManager']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/account/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getAccountHealth']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/account/accounts/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getAccountsWithCardsByAuthUserId']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete: operations['logout']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    UpdateCardRequestDto: {
      /** Format: uuid */
      accountId: string
      /** Format: uuid */
      cardId: string
      /** @enum {string} */
      status: 'ACTIVE' | 'BLOCKED' | 'FROZEN' | 'EXPIRED'
      /** Format: int64 */
      dailyLimitMinorUnits: number
      /** Format: int64 */
      monthlyLimitMinorUnits: number
    }
    UpdateCardResponseDto: {
      /** Format: uuid */
      cardId?: string
      /** Format: uuid */
      accountId?: string
      pan?: string
      /** @enum {string} */
      status?: 'ACTIVE' | 'BLOCKED' | 'FROZEN' | 'EXPIRED'
      /** Format: int64 */
      dailyLimitMinorUnits?: number
      /** Format: int64 */
      monthlyLimitMinorUnits?: number
      /** Format: date-time */
      expiresAt?: string
      /** Format: int64 */
      spendDailyLimitMinorUnits?: number
      /** Format: int64 */
      spendMonthlyLimitMinorUnits?: number
      /** @enum {string} */
      currency?: 'USD' | 'EUR' | 'CNY' | 'GBP'
    }
    VerifyAuthUserByCodeRequestDto: {
      /** Format: uuid */
      authUserId: string
      verificationCode: string
    }
    ResetPasswordRequestDto: {
      resetPasswordToken: string
      newPassword: string
    }
    UnlockAuthUserRequestDto: {
      /** Format: uuid */
      authUserId: string
    }
    BlockAuthUserRequestDto: {
      /** Format: uuid */
      authUserId?: string
    }
    ChangePasswordRequestDto: {
      oldPassword: string
      newPassword: string
    }
    ChangeAuthUserRoleRequestDto: {
      /** Format: uuid */
      authUserId: string
      /** @enum {string} */
      role: 'USER' | 'MANAGER' | 'ADMIN'
    }
    GetRecipientRequestDto: {
      /** Format: email */
      email: string
    }
    AccountResponseWithoutSensitiveInfo: {
      /** Format: uuid */
      accountId?: string
      accountNumberLast4Chars?: string
      /** @enum {string} */
      type?: 'CHECKING' | 'SAVINGS'
      /** @enum {string} */
      status?: 'ACTIVE' | 'FROZEN' | 'CLOSED'
      /** @enum {string} */
      currency?: 'USD' | 'EUR' | 'CNY' | 'GBP'
    }
    GetRecipientInfoResponseDto: {
      userInfo?: components['schemas']['UserInfoWithoutIds']
      accounts?: components['schemas']['AccountResponseWithoutSensitiveInfo'][]
    }
    UserInfoWithoutIds: {
      email?: string
      firstName?: string
      lastName?: string
    }
    GetUserInfoByManagerRequestDto: {
      /** Format: uuid */
      userId: string
    }
    GetUserInfoResponseDto: {
      /** Format: uuid */
      userProfileId?: string
      /** Format: uuid */
      autUserId?: string
      email?: string
      firstName?: string
      lastName?: string
      /** @enum {string} */
      status?: 'ACTIVE' | 'BLOCKED' | 'PENDING'
    }
    GetUserInfoWithAuthInfoResponseDto: {
      userInfo?: components['schemas']['GetUserInfoResponseDto']
      /** @enum {string} */
      role?: 'USER' | 'MANAGER' | 'ADMIN'
      /** @enum {string} */
      status?: 'ACTIVE' | 'BLOCKED' | 'PENDING' | 'FORGET_PASSWORD'
      socialAccounts?: components['schemas']['SocialAccountResponse'][]
    }
    SocialAccountResponse: {
      /** @enum {string} */
      provider?: 'GOOGLE'
      email?: string
    }
    CreateTransactionRequestDto: {
      /** Format: uuid */
      sourceAccountId: string
      /** Format: uuid */
      sourceCardId: string
      /** Format: uuid */
      targetAccountId: string
      /** Format: int64 */
      minorUnits: number
      /** @enum {string} */
      currency: 'USD' | 'EUR' | 'CNY' | 'GBP'
      /** Format: uuid */
      idempotencyKey: string
    }
    CreateTransactionResponseDto: {
      /** Format: uuid */
      transactionId?: string
      /** Format: int64 */
      minorUnits?: number
      /** @enum {string} */
      currency?: 'USD' | 'EUR' | 'CNY' | 'GBP'
      /** @enum {string} */
      status?:
        | 'FUNDS_RESERVED'
        | 'FUNDS_REQUESTED'
        | 'COMPLETED'
        | 'FAILED'
        | 'COMPENSATED'
    }
    CreateCardRequestDto: {
      /** Format: uuid */
      accountId: string
    }
    CreateCardResponseDto: {
      /** Format: uuid */
      cardId?: string
      /** Format: uuid */
      accountId?: string
      pan?: string
      /** @enum {string} */
      status?: 'ACTIVE' | 'BLOCKED' | 'FROZEN' | 'EXPIRED'
      /** Format: int64 */
      dailyLimitMinorUnits?: number
      /** Format: int64 */
      monthlyLimitMinorUnits?: number
      /** Format: date-time */
      expiresAt?: string
      /** Format: int64 */
      spendDailyLimitMinorUnits?: number
      /** Format: int64 */
      spendMonthlyLimitMinorUnits?: number
      /** @enum {string} */
      currency?: 'USD' | 'EUR' | 'CNY' | 'GBP'
    }
    SignupRequestDto: {
      /** Format: email */
      email: string
      password: string
      firstName: string
      lastName: string
    }
    LoginRequestDto: {
      /** Format: email */
      email: string
      password: string
    }
    ForgetPasswordRequestDto: {
      /** Format: email */
      email: string
    }
    UpdateAccountBalanceRequestDto: {
      /** Format: uuid */
      accountId: string
      /** Format: int64 */
      minorUnits: number
    }
    GetAccountResponseDto: {
      /** Format: uuid */
      accountId?: string
      /** Format: uuid */
      ownerUserId?: string
      accountNumber?: string
      /** @enum {string} */
      type?: 'CHECKING' | 'SAVINGS'
      /** @enum {string} */
      status?: 'ACTIVE' | 'FROZEN' | 'CLOSED'
      /** Format: int64 */
      availableBalanceMinorUnits?: number
      /** Format: int64 */
      reservedBalanceMinorUnits?: number
      /** @enum {string} */
      currency?: 'USD' | 'EUR' | 'CNY' | 'GBP'
    }
    CreateAccountRequestDto: {
      /** @enum {string} */
      type: 'CHECKING' | 'SAVINGS'
      /** @enum {string} */
      currency: 'USD' | 'EUR' | 'CNY' | 'GBP'
    }
    CreateAccountResponseDto: {
      /** Format: uuid */
      accountId?: string
      /** Format: uuid */
      ownerUserId?: string
      accountNumber?: string
      /** @enum {string} */
      type?: 'CHECKING' | 'SAVINGS'
      /** @enum {string} */
      status?: 'ACTIVE' | 'FROZEN' | 'CLOSED'
      /** Format: int64 */
      availableBalanceMinorUnits?: number
      /** Format: int64 */
      reservedBalanceMinorUnits?: number
      /** @enum {string} */
      currency?: 'USD' | 'EUR' | 'CNY' | 'GBP'
    }
    MarkNotificationsAsReadedRequestDto: {
      ids: string[]
    }
    GetRecipientResponseDto: {
      /** Format: uuid */
      accountId?: string
      accountNumberLast4Chars?: string
      /** @enum {string} */
      type?: 'CHECKING' | 'SAVINGS'
      /** @enum {string} */
      status?: 'ACTIVE' | 'FROZEN' | 'CLOSED'
      /** @enum {string} */
      currency?: 'USD' | 'EUR' | 'CNY' | 'GBP'
    }
    TransactionResponseDto: {
      /** Format: uuid */
      transactionId?: string
      /** Format: int64 */
      minorUnits?: number
      /** @enum {string} */
      currency?: 'USD' | 'EUR' | 'CNY' | 'GBP'
      /** @enum {string} */
      status?:
        | 'FUNDS_RESERVED'
        | 'FUNDS_REQUESTED'
        | 'COMPLETED'
        | 'FAILED'
        | 'COMPENSATED'
      /** Format: date-time */
      createdAt?: string
      /** Format: date-time */
      completedAt?: string
      sourceAccount?: components['schemas']['GetRecipientResponseDto']
      targetAccount?: components['schemas']['GetRecipientResponseDto']
    }
    NotificationResponseDto: {
      title?: string
      body?: string
      type?: string
    }
    GetAccountWithCardsResponseDto: {
      account?: components['schemas']['GetAccountResponseDto']
      cards?: components['schemas']['GetCardByAccountIdResponseDto'][]
    }
    GetCardByAccountIdResponseDto: {
      /** Format: uuid */
      cardId?: string
      /** Format: uuid */
      accountId?: string
      pan?: string
      /** @enum {string} */
      status?: 'ACTIVE' | 'BLOCKED' | 'FROZEN' | 'EXPIRED'
      /** Format: int64 */
      dailyLimitMinorUnits?: number
      /** Format: int64 */
      monthlyLimitMinorUnits?: number
      /** Format: date-time */
      expiresAt?: string
      /** Format: int64 */
      spendDailyLimitMinorUnits?: number
      /** Format: int64 */
      spendMonthlyLimitMinorUnits?: number
      /** @enum {string} */
      currency?: 'USD' | 'EUR' | 'CNY' | 'GBP'
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  updateCard: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateCardRequestDto']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['UpdateCardResponseDto']
        }
      }
    }
  }
  verifyUser: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['VerifyAuthUserByCodeRequestDto']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  resetPassword: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ResetPasswordRequestDto']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  verifyUserByManager: {
    parameters: {
      query?: never
      header?: never
      path: {
        authUserId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  unlockUserByManager: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UnlockAuthUserRequestDto']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  blockUserByManager: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['BlockAuthUserRequestDto']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  changePassword: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangePasswordRequestDto']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  changeAuthUserRole: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangeAuthUserRoleRequestDto']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  unfreezeAccount: {
    parameters: {
      query?: never
      header?: never
      path: {
        accountId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  unfreezeAccountByManager: {
    parameters: {
      query?: never
      header?: never
      path: {
        accountId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  freezeAccountByManager: {
    parameters: {
      query?: never
      header?: never
      path: {
        accountId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  freezeAccount: {
    parameters: {
      query?: never
      header?: never
      path: {
        accountId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  getRecipientInfo: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['GetRecipientRequestDto']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['GetRecipientInfoResponseDto']
        }
      }
    }
  }
  getUserInfoByManager: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['GetUserInfoByManagerRequestDto']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['GetUserInfoWithAuthInfoResponseDto']
        }
      }
    }
  }
  createTransaction: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateTransactionRequestDto']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['CreateTransactionResponseDto']
        }
      }
    }
  }
  createCard: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCardRequestDto']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['CreateCardResponseDto']
        }
      }
    }
  }
  signup: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SignupRequestDto']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  refresh: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequestDto']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  forgetPassword: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ForgetPasswordRequestDto']
      }
    }
    responses: {
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  withdrawAccount: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateAccountBalanceRequestDto']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['GetAccountResponseDto']
        }
      }
    }
  }
  topUpAccount: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateAccountBalanceRequestDto']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['GetAccountResponseDto']
        }
      }
    }
  }
  createAccount: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateAccountRequestDto']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['CreateAccountResponseDto']
        }
      }
    }
  }
  markAsReaded: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MarkNotificationsAsReadedRequestDto']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  getUserInfo: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['GetUserInfoWithAuthInfoResponseDto']
        }
      }
    }
  }
  getAllUserInfo: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['GetUserInfoWithAuthInfoResponseDto'][]
        }
      }
    }
  }
  getUserHealth: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': string
        }
      }
    }
  }
  getTransactionsByMe: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['TransactionResponseDto'][]
        }
      }
    }
  }
  getTransactionsByUserIdByManager: {
    parameters: {
      query?: never
      header?: never
      path: {
        userId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['TransactionResponseDto'][]
        }
      }
    }
  }
  getTransactionHealth: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': string
        }
      }
    }
  }
  getNotifications: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['NotificationResponseDto'][]
        }
      }
    }
  }
  getNotificationHealth: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': string
        }
      }
    }
  }
  getCardHealth: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': string
        }
      }
    }
  }
  googleLogin: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  getAuthHealth: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': string
        }
      }
    }
  }
  asyncApiYaml: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': string
        }
      }
    }
  }
  getAllAccountsWithCards: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['GetAccountWithCardsResponseDto'][]
        }
      }
    }
  }
  getAccountsWithCardsByOwnerIdByManager: {
    parameters: {
      query?: never
      header?: never
      path: {
        ownerUserId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['GetAccountWithCardsResponseDto'][]
        }
      }
    }
  }
  getAccountHealth: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': string
        }
      }
    }
  }
  getAccountsWithCardsByAuthUserId: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['GetAccountWithCardsResponseDto'][]
        }
      }
    }
  }
  logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
}
